---
- name: Install and configure httpd
  hosts: all
  become: true
  tasks:
    - name: Install httpd
      ansible.builtin.package:
        name: httpd

    - name: Start httpd
      ansible.builtin.service:
        name: httpd
        state: started
